variable "aws_region" {}
variable "vpc_name" {}
variable "vpc_cidr" {}
variable "public_subnet_cidr" {}
variable "ec2_name" {}
variable "ami" {}
variable "instance_type" {}
variable "monitoring" {}
variable "tags" {}
variable "email" {}
variable "key_name" {}
